name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish_docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker Login
      run: echo "$DOCKER_PASSWORD" | docker login "$DOCKER_REGISTRY_URL" -u "$DOCKER_USERNAME" --password-stdin
      env:
        DOCKER_REGISTRY_URL: docker.pkg.github.com
        DOCKER_USERNAME: codecrafters-bot
        DOCKER_PASSWORD: ${{ github.token }}
    - name: Docker Build & Push
      run: |
        repo="codecrafters-bot/redis-tester"
        pkg="redis-tester"
        tag=$(echo $GITHUB_REF | sed "s/refs\\/tags\\///")
        version_img_tag="docker.pkg.github.com/${repo}/${pkg}:${tag}"
        latest_img_tag="docker.pkg.github.com/${repo}/${pkg}:latest"
        docker build -t $version_img_tag -f Dockerfile .
        docker tag $version_img_tag $latest_img_tag
        docker push $version_img_tag
        docker push $latest_img_tag

  publish_binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
